### PR TITLE
preserve direction in adjacency matrices

### PR DESCRIPTION
**Pull request by Geometer1729**
I think it would be better to preserve direction of edges when creating the adjacency matrix.

### CODE REVIEW

**Comment by AriFordsham** [comment]
@larskuhtz Any update on this?

**Comment by larskuhtz** [comment]
Sorry, somehow this PR got lost between all other GitHub notifications.

This looks indeed like a bug. My use case for this package is with undirected graphs (symmetric edges). Therefore I probably never noticed.

I think, there should be a few unit tests for directed graphs, to confirm that the change works correctly. Let me know if you like to add those. Otherwise I can do it, too.

**Review by larskuhtz — CHANGES_REQUESTED** [review]
The changes to the cabal file are unrelated. Could you revert those? Looks good otherwise. Optionally, a few test cases for undirected graphs would be good.

**Comment by Geometer1729** [comment]
Sorry about that, when I made the PR I didn't expect us to want to make any other changes so I used master.  I'll make a new pr from a branch with just the fix and some tests.

**Pull request closed without merging**
